### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tiagozip** [amrrs/llama-4bit-colab#3]
I am getting this error:
```
# Latest step, step 6
Traceback (most recent call last):
  File "/content/GPTQ-for-LLaMa/llama_inference.py", line 108, in <module>
    model = load_quant(args.model, args.load, args.wbits)
  File "/content/GPTQ-for-LLaMa/llama_inference.py", line 27, in load_quant
    from transformers import LlamaConfig, LlamaForCausalLM 
ImportError: cannot import name 'LlamaConfig' from 'transformers' (/usr/local/lib/python3.9/dist-packages/transformers/__init__.py)
```

**Comment by iboyles** [comment]
Yes I am having the same issue.

**Comment by twobob** [comment]
yeah Im looking. its the recent commits...
we can pin the ver to like dd825c493d1e9925a5d7a6781e1e6d53046e9bad probably

**Comment by Lauorie** [comment]
Downloading (…)lve/main/config.json: 100% 427/427 [00:00<00:00, 60.5kB/s]
Loading model ...
Done.
Downloading (…)okenizer_config.json: 100% 141/141 [00:00<00:00, 60.3kB/s]
Traceback (most recent call last):
  File "/content/GPTQ-for-LLaMa/llama_inference.py", line 114, in <module>
    tokenizer = AutoTokenizer.from_pretrained(args.model)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/auto/tokenization_auto.py", line 677, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

**Comment by Tylersuard** [comment]
Same issue:

Loading model ...
Done.
Traceback (most recent call last):
  File "/content/GPTQ-for-LLaMa/llama_inference.py", line 114, in <module>
    tokenizer = AutoTokenizer.from_pretrained(args.model)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/auto/tokenization_auto.py", line 677, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

**Comment by Tylersuard** [comment]
I created a fix to solve the problem.  @amrrs please accept and merge.

**Comment by Tylersuard** [comment]
Fix: in requirements.py, change the last line to git+https://github.com/zphang/transformers@660dd6e2bbc9255aacd0e60084cf15df1b6ae00d#egg=transformers

**Comment by Tylersuard** [comment]
Ok I followed instructions, still getting this error: Traceback (most recent call last):
  File "/content/GPTQ-for-LLaMa/llama_inference.py", line 108, in <module>
    model = load_quant(args.model, args.load, args.wbits)
  File "/content/GPTQ-for-LLaMa/llama_inference.py", line 27, in load_quant
    from transformers import LlamaConfig, LlamaForCausalLM 
ImportError: cannot import name 'LlamaConfig' from 'transformers' (/usr/local/lib/python3.9/dist-packages/transformers/__init__.py)

**Comment by amrrs** [comment]
@Tylersuard I merged your PR, does it fix your problem?

**Comment by KastyaLimoneS** [comment]
I have the same issue. Followed all insructions
